export enum OFEnumShaderDataTypes {
  Unkown           = 0,
  Matrix2          = 1,
  Matrix3          = 2,
  Matrix4          = 3,
  Vector2          = 4,
  Vector3          = 5,
  Vector4          = 6,
  IntVector2       = 7,
  IntVector3       = 8,
  IntVector4       = 9,
  BooleanVector2   = 10,
  BooleanVector3   = 11,
  BooleanVector4   = 12,
  Sampler2D        = 13,
  SamplerCube      = 14,
  Float            = 15,
  Int              = 16,
  Bool             = 17,
  ICamera          = 18,
  IColor           = 19,
  ITexture         = 20
}
